### ISSUE TITLE
get_latest_management_data api returns pymongo cursor instead of dictionary

### ISSUE THREAD

**Issue by cpschult** [ibmcb/cbtool#75]
SPEC Cloud baseline scripts use 'get_latest_management_data' to retrieve deploy time measurements from each VM in an AI.  Recently the API has been returning a pymongo.cursor.Cursor instead of a dictionary containing the expected data.  It looks like the default value of variables 'samples' is forcing this behavior in 'lib/api/api_service_client.py'.

Is it expected the cursor be returned?  The baseline scripts currently expect to receive a dictionary and not the cursor.  

It is relatively easy to code around this.  The following seems to work well enough:
```
                    _mgt_metric_list = self.api.get_latest_management_data(self.cloud_name, uuid)
                    # _mgt_metric_list is returned as a Cursor instead of a list. WHY?
                    import pymongo
                    if isinstance(_mgt_metric_list,pymongo.cursor.Cursor):
                        if _mgt_metric_list.count() >= 1:
                            _mgt_metric_list = _mgt_metric_list[0]
```

**Comment by hinesmr** [comment]
Being a cursor instead of JSON is very important: You have no idea how big the data will really be, so it important for you to read each record in one-by-one in a loop so that you have control over how many mongo documents are sitting around at any given time.

You can access the documents from the cursor in a simple loop, like this:

for document in api.get_latest_management_data(...)
    print document
end

If you are sure you have enough memory to store all the documents, you can load them all into a list or whatever by yourself and operate on them, but the API should not be doing that for you.

**Comment by cpschult** [comment]
Thanks for the quick response.  There is a loop that was commented out in the baseline code with a cryptic comment.  I'll see what I can find for history on that.

**Comment by cpschult** [comment]
Closing issue per Mike's comment.  The new behavior is to return a cursor.  Reading from the cursor is easy as the examples show.
